### ISSUE TITLE
[Question/Feature request] Does fields of type array-list offers a way where we could add another button/action or even hide a button?

### ISSUE THREAD

**Issue by jesephan** [ChronicStone/vue-sweettools#10]
Hi @ChronicStone, I would like to know if fields of type `array-list` offers a way where we could add another button/action or even hide a button? The reason i'm asking we would like to another functionality where add an item but aside from delete button(default button added), We would like to have another button i.e. deactivate where add the item but it has a deactivated property. Something like this 
<img width="762" alt="image" src="https://github.com/ChronicStone/vue-sweettools/assets/6947802/56103a58-1ff8-4c61-8890-630529523623">

If not, is this something that takes time to implement?

**Comment by ChronicStone** [comment]
Hi @jesephan right now that's not possible to do, but it'd be pretty easy to implement, I could consider it but for that I'll need to know what kind of things you'd like to be able to do with these custom actions. I could think of an API like this :


```ts
interface rowApi {
   getValue(key: string): unknown
   setValue(key: string, value: unknown): void
   dependencies: Record<string, unknown>
   // ... ?? 
}


buildFormSchema({
  fields: [{
    type: 'array-list',
    key: 'array',
    label: 'array',
    fields: [...],
    actions: { moveUp: false, moveDown: false, delete: true },
    customActions: [
      {
        label: "Some action",
        icon: "xxx",
        action: (rowApi) => ...
      }
    ]
  }]
})
```

Now my question is, what kind of control / operation / internal API would you want to access. You talked about disabling a field, but this isn't possible. Disabled state control is state-driven, you can pass a function to decide whether a field should be disabled, and set dependencies to make it depend on other fields values, it's not something you can manually override.

**Comment by jesephan** [comment]
@ChronicStone thanks for quick reply. Yes that schema is preferable. Additionally something like this?

``` 
interface rowApi {
   // Maybe getValue return all fields(key/value pair) values if no specific key provided.
   getValue(key?: string): unknown
   setValue(key: string, value: unknown): void
   dependencies: Record<string, unknown>
   // ... ?? 
}

buildFormSchema({
  fields: [{
    type: 'array-list',
    key: 'array',
    label: 'array',
    fields: [...],
    actions: { moveUp: false, moveDown: false, delete: true },
    //may accept a function that returns a boolean?
    // actions: {delete: (deps): boolean => {}, addItem: (deps): boolean => {}}
    customActions: [
      {
        // so we can conditionally add this custom action?
        condition: (deps): boolean => {}
        label: "Some action",
        icon: "xxx",
        action: (rowApi) => ...
      }
    ]
  }]
})
```

**Comment by ChronicStone** [comment]
@jesephan Yep that's what I had in mind. I'll move these new options to "fieldParams", which can be either an object or a function returning an object & having access to dependencies.

I'll try to prototype this today so you can play around with it tomorrow. I'll go with this as the general idea & see what can of control / internal API I can provide here. 

That'll also require that I enhance a bit setValue / getValue utilities to be able to set a value contextually (Like if you're deep in the object tree.

**Comment by ChronicStone** [comment]
@jesephan I was pretty busy today but still managed to prototype it, works well. I need to refactor how setValue / getValue works & expend that new behavior to the field watch API as well.

Will make a release on the @next branch tomorrow morning.

If you have in mind other applications of that new feature that require other internal APIs exposed, don't hesitate to ask

**Comment by ChronicStone** [comment]
@jesephan I was pretty busy today but still managed to prototype it, works well. I need to refactor how setValue / getValue works & expend that new behavior to the field watch API as well.

Will make a release on the @next branch tomorrow morning.

If you have in mind other applications of that new feature that require other internal APIs exposed, don't hesitate to ask

**Comment by jesephan** [comment]
@ChronicStone thank you. yup adding to fieldParams make sense. Excited to have a new release. I will inform you if we have another thing to probably add on the api.

**Comment by ChronicStone** [comment]
Hi @jesephan I made an experimental release of this new feature. You can install it using the `next` tag : 

`pnpm add @chronicstone/vue-sweettools@next`

Here's an overview of the API types implementation you can use : 

```ts
export interface _ArrayField<
  FieldKey extends Narrowable = string,
  StoreData extends Record<string, unknown> = Record<string, unknown>
> {
  // ... OTHER PROPS
  actions?: {
    [key in "deleteItem" | "moveUp" | "moveDown"]?:
      | boolean
      | ((
          value: Record<string, unknown>,
          dependencies: Record<string, unknown>,
          index: number
        ) => boolean);
  } & {
    addItem?:
      | boolean
      | ((
          values: Array<Record<string, unknown>>,
          dependencies: Record<string, unknown>
        ) => boolean);
    custom?: Array<{
      label: string;
      icon: string;
      condition?: (
        value: Record<string, unknown>,
        dependencies: Record<string, unknown>
      ) => boolean;
      action: (rowApi: ArrayCustomActionApi) => void;
    }>;
  };
}
```

Here's how it can be used :  

```ts
const schema = buildFormSchema({
  fields: [
{
        label: "Array reactive",
        type: "array-tabs",
        key: "array",
        actions: {
          moveDown: false,  // DISABLE  moveDown
          moveUp: false, // DISABLE moveUp
          deleteItem: (value) => Object.values(value).every((v) => !v), // DISABLE DELETE IF ANY VALUE OF ITEM IS NOT EMPTY
          addItem: (items) => items.length < 3, // DISABLE ADD IF LENGTH >= 3
          custom: [
            {
              label: "Custom action",
              icon: "mdi:plus",
              action: (api) => {
                api.setValue(`$parent.${api.index}.item`, "HAHAHA"); // SET VALUE OF CURRENT ITEM'S PROP 'item' 
                nextTick(() =>
                  console.log("item", api.getValue("$parent.`${api.index}`.item2")) // READ VALUE PREVIOUSLY SET, AFTER NEXT TICK TO CATCH UPDATE
                );
              },
            },
          ],
        },
        fields: [
          {
            label: "Item",
            type: "text",
            key: "item",
            watch(value, { setValue }) {
              setValue("$parent.item2", value);
            },
          },
          {
            label: "Item2",
            type: "text",
            key: "item2",
          },
          {
            label: "Item2",
            type: "select",
            key: "item3",
            dependencies: [["$parent.item", "item"]],
            options: (deps) => (deps.item ? ["1", "2", "3"] : []),
          },
        ],
      },
  ]
})
```

@jesephan Open to any feedback you have

**Comment by jesephan** [comment]
I think that should be good for now @ChronicStone. Big thumbs up on this one...
``` 
....
watch(value, { setValue }) {
    setValue("$parent.item2", value);
},
```
Previously, this will not work and now its working even on other field type. 👍🏽 
I will continue testing tomorrow on the custom actions. If all good by tomorrow do you think you can do a final release tomorrow as well?

**Comment by ChronicStone** [comment]
@jesephan Yep that's what I meant by making get/set work on scoped contexts, I see a lot of cases where this can be useful, and it also standardize behavior of value access with how dépendencies works

**Comment by ChronicStone** [comment]
@jesephan v0.5.0 have just been released, and it includes this new feature.
