### ISSUE TITLE
[Feature Request] Make searchable column icon indicator customizable

### ISSUE THREAD

**Issue by jesephan** [ChronicStone/vue-sweettools#12]
Hi @ChronicStone, we would like to request to have the searchable column indicator to be customizable. That means we could set different icon, set a hover tooltip and if possible we could turn it off/on the feature.

**Comment by ChronicStone** [comment]
Hi @jesephan I kinda used the easiest solution to add the icon which is to append a magnifier character to the string containing label.

To do this, I'd need to override the default column header renderer of agGrid. But doing so might introduce interesting possibilities, like the usage of render functions to customize column header and better icons.

I'll see if I can prototype this today after work

**Comment by jesephan** [comment]
Copy @ChronicStone thanks for the support.

**Comment by ChronicStone** [comment]
@jesephan Handled with release v0.5.2
