### ISSUE TITLE
Close modal when click the browser back button

### ISSUE THREAD

**Issue by jesephan** [ChronicStone/vue-sweettools#4]
The issue is that the modal still open after the user click the browser back button. We tried to solve this outside the library but seems kind of messy and thought its better to resolve this in the library level.

**Comment by ChronicStone** [comment]
The sweettools lib does not embed Vue Router as a dependency, for several reasons. I haven't found a way yet to dynamically resolve the exposed functions of "vue-router" based off config from parent scope.

Anyway for the time being, you. can deal with this at the app level : 

```vue
<script setup lang="ts">
import { useRouter } from "vue-router" // No need to import if using nuxt
import { useFormApi } from "@chronicstone/vue-sweettools"

const formApi = useFormApi()

useRouter().beforeEach(() => {
  formApi.destroyAll()
})

</script>
```

An other way of achieving the same thing, is to access the provider ref instead calling useFormApi. Version 0.4.1 (released just now) now exposes the form API to the provider public instance, so you can do this : 

```vue
<script setup lang="ts">
import { useRouter } from "vue-router"
import { FormProvider } from "@chronicstone/vue-sweettools"

const providerRef = ref<InstanceType<typeof FormProvider>>();

useRouter().beforeEach(() => {
  providerRef.value?.destroyAll();

})

</script>

<template>
  <FormProvider ref="providerRef">
    ...
  </FormProvider />

    
</template>
```
