### ISSUE TITLE
Datatable filters value not being persists to local or session storage

### ISSUE THREAD

**Issue by jesephan** [ChronicStone/vue-sweettools#6]
When `persistency: "sessionStorage"` property is set from `buildTableSchema`, It should gracefully save the filters values to the session or local storage. This will enhance user experience where there is a page that offers a lot of filters.

**Comment by ChronicStone** [comment]
From testing I did, this works as expected. One thing you might be missing is setting a value to the `tableKey` property on the table schema.

The`tableKey` prop is used as a reference to identify the loaded table schema & restore its state. What I'll try to do for next release is use type generics to make `tableKey` required if `localStorage` or `sessionStorage` is set for`persistency`.

Try adding the tableKey & see if persistency works. If not, I'll need more context about your table, so at least the schema.

**Comment by jesephan** [comment]
@ChronicStone copy, will do another test related table key generation. That might be the case.

**Comment by ChronicStone** [comment]
Fixed with release `0.4.3`
